ekyna_news_news_admin_home:
    path: ""
    defaults: { _controller: "ekyna_news.news.controller:homeAction" }
    methods: [GET|POST]

ekyna_news_news_admin_list:
    path: /list
    defaults: { _controller: "ekyna_news.news.controller:listAction" }
    methods: [GET|POST]

ekyna_news_news_admin_new:
    path: /new
    defaults: { _controller: "ekyna_news.news.controller:newAction" }
    methods: [GET|POST]

ekyna_news_news_admin_show:
    path: /{newsId}/show
    defaults: { _controller: "ekyna_news.news.controller:showAction" }
    methods: [GET]
    requirements:
        newsId: \d+

ekyna_news_news_admin_edit:
    path: /{newsId}/edit
    defaults: { _controller: "ekyna_news.news.controller:editAction" }
    methods: [GET|POST]
    requirements:
        newsId: \d+

ekyna_news_news_admin_tinymce:
    path: /{newsId}/tinymce/{_locale}/{field}
    controller: "ekyna_news.news.controller:tinymceAction"
    methods: [GET]
    requirements:
        newsId: \d+
    defaults:
        _locale: "%locale%"
        field: content

ekyna_news_news_admin_toggle:
    path: /{newsId}/toggle/{field}
    defaults: { _controller: "ekyna_news.news.controller:toggleAction", field: enabled }
    methods: [GET|POST]
    requirements:
        newsId: \d+
        field: \w+

ekyna_news_news_admin_remove:
    path: /{newsId}/remove
    defaults: { _controller: "ekyna_news.news.controller:removeAction" }
    methods: [GET|POST]
    requirements:
        newsId: \d+
