ekyna_news_example_index:
    path: ""
    defaults: { _controller: EkynaNewsBundle:Example:index }
    methods: [GET]

ekyna_news_example_detail:
    path: /{slug}
    defaults: { _controller: EkynaNewsBundle:Example:detail }
    methods: [GET]
    requirements:
        slug: "[a-zA-Z0-9-]+"
